from __future__ import annotations
from typing import Any, Dict, Optional

__all__ = [
    "CTk",
    "CTkLabel",
    "CTkFrame",
    "set_appearance_mode",
    "set_default_color_theme",
]

def set_appearance_mode(mode: str) -> None: ...

def set_default_color_theme(theme: Optional[str] = None) -> None: ...

class CTk:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def pack(self, **kwargs: Any) -> None: ...
    def grid(self, **kwargs: Any) -> None: ...
    def configure(self, require_redraw: bool = False, **kwargs: Any) -> None: ...
    def protocol(self, name: str, func: Any) -> None: ...
    def mainloop(self) -> None: ...
    def title(self, title: str) -> None: ...
    def geometry(self, geometry: str) -> None: ...
    def after(self, ms: int, func: Any = None) -> Any: ...
    def destroy(self) -> None: ...

class CTkLabel(CTk):
    image: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class CTkFrame(CTk):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
